[package]
name = "chess-lib-rs"
version = "0.1.0"
edition = "2021"
authors = [
    "Amirthanathan R"
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.9.5"
